LineLength:
  Enabled: false

MethodLength:
  Max: 30

Documentation:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

PerlBackrefs:
  Enabled: false

AllCops:
  Includes:
    - Rakefile
    - Gemfile
    - config.ru
  Excludes:
    - build/**
